// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbzcflxmbadybtvfoqbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiemNmbHhtYmFkeWJ0dmZvcWJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzU1OTMsImV4cCI6MjA1OTk1MTU5M30.v4St19ETDB5pnMLhpCObJoUjg6uLz7PiZYCiaNq8cKM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);